### ISSUE TITLE
叠加地图出错

### ISSUE THREAD

**Issue by abanger** [YvZheng/pycwr#14]
叠加地图出错
**pycwr==0.2.13**

(radar) D:\weather\pycwr2>python scripts\LaunchGUI.py
Traceback (most recent call last):
  File "C:\Anaconda3\envs\radar\lib\site-packages\pycwr\GraphicalInterface\RadarInterface.py", line 287, in on_listWidget_itemDoubleClicked
    self.actionwithmap.isChecked(), self.actioncontinuous.isChecked())
  File "C:\Anaconda3\envs\radar\lib\site-packages\pycwr\GraphicalInterface\RadarInterface.py", line 403, in plot_graph_PPI
    field_name[product], continuously=continuously)
  File "C:\Anaconda3\envs\radar\lib\site-packages\pycwr\draw\SingleRadarPlotMap.py", line 104, in GUI_plot
    clabel=clabel, continuously=continuously)
  File "C:\Anaconda3\envs\radar\lib\site-packages\pycwr\draw\SingleRadarPlotMap.py", line 211, in plot_ppi_map
    pm = ax.pcolormesh(lon, lat, radar_data, transform=projection, cmap=cmap, norm = norm, zorder=4)
  File "C:\Anaconda3\envs\radar\lib\site-packages\cartopy\mpl\geoaxes.py", line 1459, in pcolormesh
    result = self._pcolormesh_patched(*args, **kwargs)
  File "C:\Anaconda3\envs\radar\lib\site-packages\cartopy\mpl\geoaxes.py", line 1491, in _pcolormesh_patched
    X, Y, C = self._pcolorargs('pcolormesh', *args, allmatch=allmatch)
  File "C:\Anaconda3\envs\radar\lib\site-packages\matplotlib\axes\_axes.py", line 5717, in _pcolorargs
    'x and y arguments to pcolormesh cannot have '
ValueError: x and y arguments to pcolormesh cannot have non-finite values or be of type numpy.ma.core.MaskedArray with masked values

**Comment by abanger** [comment]
无站点信息，建议提示。
