### ISSUE TITLE
部分数据文件graph.plot_vcs出错

### ISSUE THREAD

**Issue by abanger** [YvZheng/pycwr#16]
部分数据文件graph.plot_vcs出错，部分正常运行

环境：python=3.7,cartopy=0.17.0,pycwr=0.2.13

如下出错信息：
Traceback (most recent call last):
  File "pycwr.py", line 48, in <module>
    graph.plot_vcs(ax, (0,0), (0, 230), "dBZ", cmap="pyart_NWSRef")
  File "d:\apps\Anaconda3\envs\radar\lib\site-packages\pycwr\draw\RadarPlot.py", line 91, in plot_vcs
    mesh_xy, mesh_z, field_data = self.Radar.get_vcs_data(start_point, end_point, field_name)
  File "d:\apps\Anaconda3\envs\radar\lib\site-packages\pycwr\core\NRadar.py", line 196, in get_vcs_data
    range=xr.DataArray(ranges, dims="vcs_r"), method="nearest") ##选取插值的点
  File "d:\apps\Anaconda3\envs\radar\lib\site-packages\xarray\core\dataarray.py", line 1051, in sel
    **indexers_kwargs,
  File "d:\apps\Anaconda3\envs\radar\lib\site-packages\xarray\core\dataset.py", line 2014, in sel
    self, indexers=indexers, method=method, tolerance=tolerance
  File "d:\apps\Anaconda3\envs\radar\lib\site-packages\xarray\core\coordinates.py", line 392, in remap_label_indexers
    obj, v_indexers, method=method, tolerance=tolerance
  File "d:\apps\Anaconda3\envs\radar\lib\site-packages\xarray\core\indexing.py", line 260, in remap_label_indexers
    idxr, new_idx = convert_label_indexer(index, label, dim, method, tolerance)
  File "d:\apps\Anaconda3\envs\radar\lib\site-packages\xarray\core\indexing.py", line 190, in convert_label_indexer
    indexer = get_indexer_nd(index, label, method, tolerance)
  File "d:\apps\Anaconda3\envs\radar\lib\site-packages\xarray\core\indexing.py", line 103, in get_indexer_nd
    flat_indexer = index.get_indexer(flat_labels, method=method, tolerance=tolerance)
  File "d:\apps\Anaconda3\envs\radar\lib\site-packages\pandas\core\indexes\base.py", line 2985, in get_indexer
    "Reindexing only valid with uniquely" " valued Index objects"
pandas.core.indexes.base.InvalidIndexError: Reindexing only valid with uniquely valued Index objects

**Comment by bugsuse** [comment]
能否给出能够重现上述问题的示例数据，从而帮助我们找到问题 @abanger

**Comment by abanger** [comment]
> 能否给出能够重现上述问题的示例数据，从而帮助我们找到问题 @abanger

谢谢，等回去再发。

**Comment by YvZheng** [comment]
yuzheng1206@outlook.com

**Comment by bugsuse** [comment]
@abanger libravo@foxmail.com 给我们谁发都可以

**Comment by abanger** [comment]
@bugsuse  @YvZheng 已发，谢谢

**Comment by bugsuse** [comment]
@abanger 使用你给的数据我没能重现上述错误
相关库版本：
numpy=1.18.1
xarray=0.13.0
cartopy=0.17.0

`import matplotlib.pyplot as plt
from pycwr.io.auto_io import radar_io 
from pycwr.draw.RadarPlot import Graph

filename = '2020012221.55A'
basedata = radar_io(filename)
PRD = basedata.ToPRD()
graph = Graph(PRD)

fig, ax = plt.subplots(figsize=(12, 9))
graph.plot_vcs(ax, (0,0), (0, 230), "dBZ", cmap="pyart_NWSRef")
`

![test](https://user-images.githubusercontent.com/16102453/74336556-78e90300-4dd9-11ea-97cc-eed5dce2dc83.png)

**Comment by abanger** [comment]
@bugsuse 谢谢。
您用的是pycwr=0.2.14，出错环境是pycwr=0.2.13，测试后再反馈。

**Comment by bugsuse** [comment]
@abanger 出错是因为此文件第6个仰角扫描时的第175和176个方位角相同，均为`171.826171875`，而xarray在使用`.sel`选择数据时，其索引应该是独一无二的，不能是重复的。所以导致出现上述错误，我认为这可能是非常特殊的个例。如果其他相同格式的大部分文件没有出错的话，建议关闭此issue。

**Comment by abanger** [comment]
> @abanger 出错是因为此文件第6个仰角扫描时的第175和176个方位角相同，均为`171.826171875`，而xarray在使用`.sel`选择数据时，其索引应该是独一无二的，不能是重复的。所以导致出现上述错误，我认为这可能是非常特殊的个例。如果其他相同格式的大部分文件没有出错的话，建议关闭此issue。

感谢，还有其他文件也有这样问题，至于有多少数据有问题，待与数据提供方咨询。这样应是雷达数据处理的问题。
谢谢！
