### ISSUE TITLE
显示不了0.5度

### ISSUE THREAD

**Issue by aliny2003** [YvZheng/pycwr#17]
from pycwr.io.auto_io import radar_io
from pycwr.draw.SingleRadarPlotMap import RadarGraphMap
import matplotlib.pyplot as plt

filename = r"D:\cl\Z9591.20200214.075822.AR2.bz2"

PRD = radar_io(filename).ToPRD()
graph = RadarGraphMap(PRD)
graph.plot(0, "dBZ")
plt.show()

----------------------------------------------

(base) C:\Users\Administrator.USER-20190423EA>C:/ProgramData/Anaconda3/python.exe c:/Users/Administrator.USER-20190423EA/Desktop/pycwr/test.py
Traceback (most recent call last):
  File "c:/Users/Administrator.USER-20190423EA/Desktop/pycwr/test.py", line 47, in <module>
    graph.plot(0, "dBZ")
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycwr-0.2.10-py3.7.egg\pycwr\draw\SingleRadarPlot.py", line 55, in plot
    clabel=clabel, dark=dark, continuously=continuously)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycwr-0.2.10-py3.7.egg\pycwr\draw\SingleRadarPlot.py", line 142, in simple_plot_ppi
    assert radar_data is not None, "radar_data should not be None!"
AssertionError: radar_data should not be None!

**Comment by YvZheng** [comment]
版本问题，更新可解决。#17
