### ISSUE TITLE
Support GeoAxes passed by proplot

### ISSUE THREAD

**Issue by zxdawn** [YvZheng/pycwr#19]
## Problem
The ax passed by proplot is `GeoAxes` instead of `GeoAxesSubplot`.

## Code
```
import cartopy.crs as ccrs
import proplot as plot
from pycwr.draw.RadarPlot import Graph, GraphMap
from pycwr.io.auto_io import radar_io

proj = ccrs.PlateCarree()
f, axs = plot.subplots(proj=proj)

dir = '/yin_raid/xin/data/radar/guangzhou/'
file = "Z_RADR_I_Z9200_20160506100000_O_DOR_SA_CAP.bin.bz2"
data = radar_io(dir+file)
NRadar = data.ToPRD()

graph = GraphMap(NRadar, ccrs.PlateCarree())
ax=axs[0]
graph.plot_crf_map(ax)
```

## Error
```
Traceback (most recent call last):
  File "crf.py", line 21, in <module>
    graph.plot_crf_map(ax)
  File "/yin_raid/xin/miniconda3/envs/pycwr/lib/python3.7/site-packages/pycwr-0.2.14-py3.7-linux-x86_64.egg/pycwr/draw/RadarPlot.py", line 368, in plot_crf_map
    assert isinstance(ax, cartopy.mpl.geoaxes.GeoAxesSubplot), "axes is not cartopy axes!"
AssertionError: axes is not cartopy axes!
```

## Solution
```
assert isinstance(ax, (cartopy.mpl.geoaxes.GeoAxes, cartopy.mpl.geoaxes.GeoAxesSubplot)), "axes is not cartopy axes!"
```

**Comment by zxdawn** [comment]
@bugsuse @bugsuse What do you think of supporting `proplot`?

**Comment by zxdawn** [comment]
Maybe we can just using `GeoAxes` and `GeoAxesSubplot` to distinguish `proplot` and `matplotlib`? @YvZheng Are axes passed by matplotlib all `GeoAxesSubplot`?
