### ISSUE TITLE
0.4.0安装环境

### ISSUE THREAD

**Issue by jiangleads** [YvZheng/pycwr#51]
安装的时候出现了若干bug，发现是numpy和matplotlib版本不兼容，最后用了这个环境安装成功
matplotlib<=3.6
python=3.10 
numpy=1.26.4
[requirements.txt](https://github.com/user-attachments/files/16184205/requirements.txt)

**Comment by jiangleads** [comment]
pycwr/draw/VerticalSectionPlot.py脚本第231行笔误，
min_h, max_h = heigh
应该是
min_h, max_h = height

**Comment by jiangleads** [comment]
GUI界面无法绘制“差分反射率”、“多普勒速度”等变量，经过检查发现，是因为色标注册添加了“copy_”这个前缀，导致无法识别色标。报错如下
`Traceback (most recent call last):                                                                                                                             File "/home/lzjiang/anaconda3/envs/cwr/lib/python3.10/site-packages/pycwr/GraphicalInterface/RadarInterface.py", line 512, in on_radioButton_13_clicked        self.plot_graph_PPI(self.radar_dat, self.find_level_in_groupBox(), self.find_var_in_groupBox(),                                                            File "/home/lzjiang/anaconda3/envs/cwr/lib/python3.10/site-packages/pycwr/GraphicalInterface/RadarInterface.py", line 396, in plot_graph_PPI                   self.pm = RadarGraph.GUI_plot(radar, self.fig, self.ax, self.cax, level, \                                                                                 File "/home/lzjiang/anaconda3/envs/cwr/lib/python3.10/site-packages/pycwr/draw/SingleRadarPlot.py", line 87, in GUI_plot                                       RadarGraph.plot_ppi(fig, ax, cx, x, y, field, normvar=(vmin, vmax),                                                                                        File "/home/lzjiang/anaconda3/envs/cwr/lib/python3.10/site-packages/pycwr/draw/SingleRadarPlot.py", line 208, in plot_ppi                                      cmaps = plt.get_cmap(cmap)                                                                                                                                 File "/home/lzjiang/anaconda3/envs/cwr/lib/python3.10/site-packages/matplotlib/pyplot.py", line 2101, in get_cmap                                              return cm._get_cmap(name=name, lut=lut)                                                                                                                    File "/home/lzjiang/anaconda3/envs/cwr/lib/python3.10/site-packages/matplotlib/cm.py", line 300, in _get_cmap                                                  _api.check_in_list(sorted(_colormaps), name=name)                                                                                                          File "/home/lzjiang/anaconda3/envs/cwr/lib/python3.10/site-packages/matplotlib/_api/__init__.py", line 131, in check_in_list                                   raise ValueError(msg)                                                                                                                                    ValueError: 'pyart_RefDiff' is not a valid value for name; supported values are 'Accent', 'Accent_r', 'Blues', 'Blues_r', 'BrBG', 'BrBG_r', 'BuGn', 'BuGn_r', 'BuPu', 'BuPu_r', 'CMRmap', 'CMRmap_r', 'CN_hcl', 'CN_ref', 'CN_vel', 'Dark2', 'Dark2_r', 'GnBu', 'GnBu_r', 'Greens', 'Greens_r', 'Greys', 'Greys_r', 'OrRd', 'OrRd_r', 'Oranges', 'Oranges_r', 'PRGn', 'PRGn_r', 'Paired', 'Paired_r', 'Pastel1', 'Pastel1_r', 'Pastel2', 'Pastel2_r', 'PiYG', 'PiYG_r', 'PuBu', 'PuBuGn', 'PuBuGn_r', 'PuBu_r', 'PuOr', 'PuOr_r', 'PuRd', 'PuRd_r', 'Purples', 'Purples_r', 'RdBu', 'RdBu_r', 'RdGy', 'RdGy_r', 'RdPu', 'RdPu_r', 'RdYlBu', 'RdYlBu_r', 'RdYlGn', 'RdYlGn_r', 'Reds', 'Reds_r', 'Set1', 'Set1_r', 'Set2', 'Set2_r', 'Set3', 'Set3_r', 'Spectral', 'Spectral_r', 'Wistia', 'Wistia_r', 'YlGn', 'YlGnBu', 'YlGnBu_r', 'YlGn_r', 'YlOrBr', 'YlOrBr_r', 'YlOrRd', 'YlOrRd_r', 'afmhot', 'afmhot_r', 'autumn', 'autumn_r', 'binary', 'binary_r', 'bone', 'bone_r', 'brg', 'brg_r', 'bwr', 'bwr_r', 'cividis', 'cividis_r', 'cool', 'cool_r', 'coolwarm', 'coolwarm_r', 'copper', 'copper_r', 'copy_pyart_BlueBrown10', 'copy_pyart_BlueBrown10_r', 'copy_pyart_BlueBrown11', 'copy_pyart_BlueBrown11_r', 'copy_pyart_BrBu10', 'copy_pyart_BrBu10_r', 'copy_pyart_BrBu12', 'copy_pyart_BrBu12_r', 'copy_pyart_Bu10', 'copy_pyart_Bu10_r', 'copy_pyart_Bu7', 'copy_pyart_Bu7_r', 'copy_pyart_BuDOr12', 'copy_pyart_BuDOr12_r', 'copy_pyart_BuDOr18', 'copy_pyart_BuDOr18_r', 'copy_pyart_BuDRd12', 'copy_pyart_BuDRd12_r', 'copy_pyart_BuDRd18', 'copy_pyart_BuDRd18_r', 'copy_pyart_BuGr14', 'copy_pyart_BuGr14_r', 'copy_pyart_BuGy8', 'copy_pyart_BuGy8_r', 'copy_pyart_BuOr10', 'copy_pyart_BuOr10_r', 'copy_pyart_BuOr12', 'copy_pyart_BuOr12_r', 'copy_pyart_BuOr8', 'copy_pyart_BuOr8_r', 'copy_pyart_BuOrR14', 'copy_pyart_BuOrR14_r', 'copy_pyart_Carbone11', 'copy_pyart_Carbone11_r', 'copy_pyart_Carbone17', 'copy_pyart_Carbone17_r', 'copy_pyart_Carbone42', 'copy_pyart_Carbone42_r', 'copy_pyart_Cat12', 'copy_pyart_Cat12_r', 'copy_pyart_EWilson17', 'copy_pyart_EWilson17_r', 'copy_pyart_GrMg16', 'copy_pyart_GrMg16_r', 'copy_pyart_Gray5', 'copy_pyart_Gray5_r', 'copy_pyart_Gray9', 'copy_pyart_Gray9_r', 'copy_pyart_HomeyerRainbow', 'copy_pyart_HomeyerRainbow_r', 'copy_pyart_LangRainbow12', 'copy_pyart_LangRainbow12_r', 'copy_pyart_NWSRef', 'copy_pyart_NWSRef_r', 'copy_pyart_NWSVel', 'copy_pyart_NWSVel_r', 'copy_pyart_NWS_SPW', 'copy_pyart_NWS_SPW_r', 'copy_pyart_PD17', 'copy_pyart_PD17_r', 'copy_pyart_RRate11', 'copy_pyart_RRate11_r', 'copy_pyart_RdYlBu11b', 'copy_pyart_RdYlBu11b_r', 'copy_pyart_RefDiff', 'copy_pyart_RefDiff_r', 'copy_pyart_SCook18', 'copy_pyart_SCook18_r', 'copy_pyart_StepSeq25', 'copy_pyart_StepSeq25_r', 'copy_pyart_SymGray12', 'copy_pyart_SymGray12_r', 'copy_pyart_Theodore16', 'copy_pyart_Theodore16_r', 'copy_pyart_Wild25', 'copy_pyart_Wild25_r', 'copy_pyart_balance', 'copy_pyart_balance_r', 'copy_pyart_ref_r', 'copy_pyart_vel_r', 'cubehelix', 'cubehelix_r', 'flag', 'flag_r', 'gist_earth', 'gist_earth_r', 'gist_gray', 'gist_gray_r', 'gist_heat', 'gist_heat_r', 'gist_ncar', 'gist_ncar_r', 'gist_rainbow', 'gist_rainbow_r', 'gist_stern', 'gist_stern_r', 'gist_yarg', 'gist_yarg_r', 'gnuplot', 'gnuplot2', 'gnuplot2_r', 'gnuplot_r', 'gray', 'gray_r', 'hot', 'hot_r', 'hsv', 'hsv_r', 'inferno', 'inferno_r', 'jet', 'jet_r', 'magma', 'magma_r', 'nipy_spectral', 'nipy_spectral_r', 'ocean', 'ocean_r', 'pink', 'pink_r', 'plasma', 'plasma_r', 'prism', 'prism_r', 'rainbow', 'rainbow_r', 'seismic', 'seismic_r', 'spring', 'spring_r', 'summer', 'summer_r', 'tab10', 'tab10_r', 'tab20', 'tab20_r', 'tab20b', 'tab20b_r', 'tab20c', 'tab20c_r', 'terrain', 'terrain_r', 'turbo', 'turbo_r', 'twilight', 'twilight_r', 'twilight_shifted', 'twilight_shifted_r', 'viridis', 'viridis_r', 'winter', 'winter_r'  `
pycwr/draw/colormap/cm.py脚本第170行，改为full_name = 'pyart_' + name。
经过修改后，可以绘图了。
上述两处修改已提交request。
